### ISSUE TITLE
API change about authentication ?

### ISSUE THREAD

**Issue by obiwankennedy** [george99g/QDiscord#5]
Hi, 

I wrote a bot thanks to your qdiscord lib. I worked perfectly for several weeks but todays the bot went online and now if I start it manually. It says : Login fails. I’m wondering if there is a change in the authentication process. 

I got no clue about why it happens only now. Do your bots are working ?

**Comment by magiruuvelvet** [comment]
The Discord devs have commited a new change to the API several weeks ago. If you re-login/auth too often within a short time period the token is reset without any kind of notification. The devs highly recommend to generate a separate token for development. This will happen pretty often during bot development in the future. Personally I find this change is just crap and I just don't get it why they did this in the first place.

**Comment by magiruuvelvet** [comment]
As an extend you should know that QDiscord has a connection loop problem right now. This triggers the token resetter of the Discord API.
