### ISSUE TITLE
connection loop problem

### ISSUE THREAD

**Issue by obiwankennedy** [george99g/QDiscord#6]
As discuss in #5, this problem may cause token to be reset. 

Have you any idea how to fix it ?
I don't know much about discord api oath and stuff like that but i can help.

Let me know if you need help about that problem.

**Comment by george99g** [comment]
Attempting to replay the missed events on reconnect instead of just logging in again should fix it. That entire component is up for a refactor, anyway.

Check the projects section to see what I have planned for the library.

**Comment by george99g** [comment]
This has been fixed in the upcoming WebSocket refactor.
